import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";
import Head from "next/head";;

const opnsns = Open_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Formanis",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Head>
        <link rel="stylesheet" type="text/css" charSet="UTF-8" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick.min.css" />
        <link
          rel="stylesheet"
          type="text/css"
          href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick-theme.min.css"
        />
        <link rel="apple-touch-icon" href="/favicon.ico" sizes="any" />
      </Head>
      <html lang="en">
        <body className={opnsns.className} suppressHydrationWarning={true}>
          {children}
        </body>
      </html>
    </>
  );
}
